# Generated by Django 4.2.20 on 2025-03-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('binary_compare', '二进制代码比对'), ('vulnerability', '漏洞分析')], max_length=20, verbose_name='分析类型')),
                ('file1', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件1')),
                ('file2', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='文件2')),
                ('similarity_score', models.FloatField(verbose_name='相似度得分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分析历史',
                'verbose_name_plural': '分析历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
