# Generated by Django 4.2.20 on 2025-03-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysishistory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysishistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='result_image',
        ),
    ]
