# Generated by Django 4.2.20 on 2025-03-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_analysishistory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='remarks',
            field=models.TextField(blank=True, help_text='存储漏洞类型或其他分析结果', null=True, verbose_name='备注'),
        ),
    ]
